const constant = {};
constant.APP_SET_ALERT_MESSAGE = "APP_SET_ALERT_MESSAGE";
constant.APP_CLOSE_ALERT_MESSAGE = "APP_CLOSE_ALERT_MESSAGE";
constant.SET_LOADING_STATUS = "SET_LOADING_STATUS";

constant.SET_ADMIN_LOGGED_IN = "SET_ADMIN_LOGGED_IN";
// Bicycle Showing and update delete by amdin
constant.FETCH_BICYCLES_DATA_SUCCESS = "FETCH_BICYCLES_DATA_SUCCESS";
constant.FETCH_SINGLE_BICYCLE_DATA_SUCCESS =
  "FETCH_SINGLE_BICYCLE_DATA_SUCCESS";
constant.ADD_BICYCLE_SUCCESS = "ADD_BICYCLE_SUCCESS";
constant.DELETE_BICYCLE_SUCCESS = "DELETE_BICYCLE_SUCCESS";
constant.UPDATE_BICYCLE_SUCCESS = "UPDATE_BICYCLE_SUCCESS";

// Order Bicycle By User
constant.USER_CHANGE_BICYCLE_QUANTITY = "USER_CHANGE_BICYCLE_QUANTITY";
constant.USER_ORDER_CONFIRM_SUCCESS = "USER_ORDER_CONFIRM_SUCCESS";
constant.FETCH_USER_ORDERS_SUCCESS = "FETCH_USER_ORDERS_SUCCESS";
constant.ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
constant.FETCH_ALL_ORDERS_SUCCESS = "FETCH_ALL_ORDERS_SUCCESS";
constant.CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";

// Review types
constant.FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
constant.ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";

// Admin Manage
constant.FETCH_ALL_ADMIN_SUCCESS = "FETCH_ALL_ADMIN_SUCCESS";
constant.ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS";
constant.DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";

export default constant;
